version: '3'
services:
  database:
    image: postgres:15
    container_name: classroom-1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=classroom
      - POSTGRES_USER=classroom
      - POSTGRES_PASSWORD=classroom